### ISSUE TITLE
Microbug on frontend section

### ISSUE THREAD

**Issue by Oleh-Code** [pytvo/FitnessApp#1]
@geno3a 
<img width="399" alt="Screenshot 2024-02-21 at 17 59 35" src="https://github.com/pytvo/FitnessApp/assets/67587036/ae356aa8-41f5-4012-b08e-525110d97865">

### Some days that have high percentage don't have center position
IDK how to fix it, maybe you have some ideas about it :/
**If it's not important, let it be like that, I don't care, we can return to this later :)**

**Comment by geno3a** [comment]
Knew about that problem, I will try to fix that, but i can not promise that i fix it.

**Comment by geno3a** [comment]
Fix the issue(at least on Pixel 7 and iPhone 15 pro max
